<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="models.example.conf" CopyToOutputDirectory="PreserveNewest" />
    <None Update="settings.example.conf" CopyToOutputDirectory="PreserveNewest" />
    <None Update="system-prompt.example.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="system-prompt.ru.example.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
